name: CI - Build & Test & Quality (Develop)
run-name: CI run by ${{ github.actor }} on develop
on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  build_test_and_quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v6
      
      - name: Set up node 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
      
      - name: Install project dependencies
        run: npm install
      
      - name: Run test
        run: npm run test
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-north-1
          role-to-assume: arn:aws:iam::225989349749:role/scc-github-actions-role
          audience: sts.amazonaws.com
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Build, tag, and push docker image to Amazon ECR
        id: build-def
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: scc-frontend
          IMAGE_TAG: ${{ github.sha }}
        with:
          IMAGE: $REGISTRY/$REPOSITORY:$IMAGE_TAG
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Download task definition 
        run: |
          aws ecs describe-task-definition --task-definition scc-frontend-task --query "taskDefinition" --output json > task-definition.json

      - name: Fill in new image ID in task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json 
          container-name: scc-frontend 
          image: ${{ steps.build-def.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1 
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: scc-frontend-service
          cluster: scc-cluster

